
dx=[0.00002,1,1,0.00002,1,1,0.00002,1,1,0.00002,1,0.00002,1,1,0.00002,1,1,0.00002,1,1,0.00002,1,1,0.00002,1,1,1,0.00002,1,1;];
marker={'+:','+-','+--',...
    'o:','o-','o--',...
    '*:','*-','*--',...
    'x:','x-','x--',...
    's:','s-','s--',...
    'd:','d-','d--',...
    '^:','^-','^--',...
    'v:','v-','v--','^-.',...
    '>:','>-','>--',...
    '<:','<-','<--'};

marker2={'+','+','+',...
    'o','o','o',...
    '*','*','*',...
    'x','x','x',...
    's','s','s',...
    'd','d','d',...
    '^','^','^',...
    'v','v','v','^',...
    '>','>','>',...
    '<','<','<'};
line2={':','-','--',...
    ':','-','--',...
    ':','-','--',...
    ':','-','--',...
    ':','-','--',...
    ':','-','--',...
    ':','-','--',...
    ':','-','--','-.',...
    ':','-','--',...
    ':','-','--'};
phen = {'w_{ANF \rightarrow TS}',...
    'n_{LSR \rightarrow TS}',...
    'n_{HSR \rightarrow TS}',...
    'w_{ANF \rightarrow DS}',...
    'n_{LSR \rightarrow DS}',...
    'n_{HSR \rightarrow DS}',...
    'w_{ANF \rightarrow TV}',...
    'n_{LSR \rightarrow TV}',...
    'n_{HSR \rightarrow TV}',...
    'w_{LSR \rightarrow GLG}',...
    'n_{LSR \rightarrow GLG}',...
    'w_{DS \rightarrow TS}',...
    'n_{DS \rightarrow TS}',...
    's_{DS \rightarrow TS}',...
    'w_{TV \rightarrow TS}',...
    'n_{TV \rightarrow TS}',...
    's_{TV \rightarrow TS}',...
    'w_{GLG \rightarrow TS}',...
    'n_{GLG \rightarrow TS}',...
    's_{GLG \rightarrow TS}',...
    'w_{DS \rightarrow TV}',...
    'n_{DS \rightarrow TV}',...
    's_{DS \rightarrow TV}',...
    'w_{TV \rightarrow DS}',...
    'n_{TV \rightarrow DS}',...
    's_{TV \rightarrow DS}',...
    'o_{DS \rightarrow TV}',...
    'w_{GLG\rightarrow DS}',...
    'n_{GLG \rightarrow DS}',...
    's_{GLG \rightarrow DS}'};

Connection= {'+  ANF \rightarrow TS'  
'\circ  ANF \rightarrow DS'   
'\ast  ANF \rightarrow TV'
'\times  LSR \rightarrow GLG' 
'\Box  DS \rightarrow TS'
'\diamond  TV \rightarrow TS'   
'\vartriangle  GLG \rightarrow TS'
'\triangledown  DS \rightarrow TV'
'\triangleright  TV \rightarrow DS'    
'\triangleleft  GLG \rightarrow DS'};